version: "3.9"

services:
  api:
    container_name: fast-talk-api
    image: node:16-alpine
    restart: always
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./backend:/usr/app
    working_dir: /usr/app
    command: npm run dev
  mobile:
    container_name: fast-talk-mobile
    build: ./mobile
    restart: always
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    working_dir: /usr/app
    volumes:
      - ./mobile/:/usr/app
    depends_on:
      - api
    command: npm start
    